"""add revoked tokens table and recovery hash

Revision ID: 3b565fdcbe1f
Revises: 474a24018a42
Create Date: 2026-06-12 21:57:45.123535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import sys
import os
# Ensure parent directory is in path to import models
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import models

# revision identifiers, used by Alembic.
revision = '3b565fdcbe1f'
down_revision = '474a24018a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=True)

    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.alter_column('phase',
               existing_type=sa.VARCHAR(length=50),
               type_=models.EncryptedString(),
               existing_nullable=False)
        batch_op.alter_column('energy_level',
               existing_type=sa.INTEGER(),
               type_=models.EncryptedInt(),
               existing_nullable=True)
        batch_op.alter_column('pelvic_pain',
               existing_type=sa.INTEGER(),
               type_=models.EncryptedInt(),
               existing_nullable=True)
        batch_op.alter_column('flow_intensity',
               existing_type=sa.INTEGER(),
               type_=models.EncryptedInt(),
               existing_nullable=True)
        batch_op.alter_column('back_pain',
               existing_type=sa.INTEGER(),
               type_=models.EncryptedInt(),
               existing_nullable=True)
        batch_op.alter_column('sleep_quality',
               existing_type=sa.INTEGER(),
               type_=models.EncryptedInt(),
               existing_nullable=True)
        batch_op.alter_column('basal_body_temp',
               existing_type=sa.FLOAT(),
               type_=models.EncryptedFloat(),
               existing_nullable=True)
        batch_op.alter_column('mood_toggles',
               existing_type=sqlite.JSON(),
               type_=models.EncryptedJSON(),
               existing_nullable=True)
        batch_op.alter_column('symptom_tags',
               existing_type=sqlite.JSON(),
               type_=models.EncryptedJSON(),
               existing_nullable=True)
        batch_op.alter_column('lifestyle_actions',
               existing_type=sqlite.JSON(),
               type_=models.EncryptedJSON(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('recovery_hash')

    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.alter_column('lifestyle_actions',
               existing_type=models.EncryptedJSON(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('symptom_tags',
               existing_type=models.EncryptedJSON(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('mood_toggles',
               existing_type=models.EncryptedJSON(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('basal_body_temp',
               existing_type=models.EncryptedFloat(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('sleep_quality',
               existing_type=models.EncryptedInt(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('back_pain',
               existing_type=models.EncryptedInt(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('flow_intensity',
               existing_type=models.EncryptedInt(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('pelvic_pain',
               existing_type=models.EncryptedInt(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('energy_level',
               existing_type=models.EncryptedInt(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('phase',
               existing_type=models.EncryptedString(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))

    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
