"""Initial schema with User and DailyLog tables

Revision ID: 474a24018a42
Revises: 
Create Date: 2026-06-02 08:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474a24018a42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('cycle_length_baseline', sa.Integer(), nullable=False),
    sa.Column('period_length_baseline', sa.Integer(), nullable=False),
    sa.Column('has_pcos', sa.Boolean(), nullable=False),
    sa.Column('has_pmdd', sa.Boolean(), nullable=False),
    sa.Column('has_endo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('pelvic_pain', sa.Integer(), nullable=True),
    sa.Column('flow_intensity', sa.Integer(), nullable=True),
    sa.Column('back_pain', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('basal_body_temp', sa.Float(), nullable=True),
    sa.Column('mood_toggles', sa.JSON(), nullable=True),
    sa.Column('symptom_tags', sa.JSON(), nullable=True),
    sa.Column('lifestyle_actions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_user_log_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_logs')
    op.drop_table('users')
    # ### end Alembic commands ###