"""add_dek_fields

Revision ID: 8f73fb177958
Revises: 3b565fdcbe1f
Create Date: 2026-06-14 21:53:36.885477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f73fb177958'
down_revision = '3b565fdcbe1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_dek_pin', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_dek_recovery', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('encrypted_dek_recovery')
        batch_op.drop_column('encrypted_dek_pin')

    # ### end Alembic commands ###
