"""add medical disclaimer columns

Revision ID: da411c616a11
Revises: f6170b6fc591
Create Date: 2026-06-20 21:04:46.051099

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = 'da411c616a11'
down_revision = 'f6170b6fc591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_logs_log_date'), ['log_date'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disclaimer_accepted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('disclaimer_signed_name', models.EncryptedString(), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('disclaimer_signed_name')
        batch_op.drop_column('disclaimer_accepted')

    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_logs_log_date'))

    # ### end Alembic commands ###
