"""add has_onboarded to user

Revision ID: f6170b6fc591
Revises: bf7f2780b340
Create Date: 2026-06-15 20:46:08.150443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6170b6fc591'
down_revision = 'bf7f2780b340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_onboarded', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_onboarded')
    # ### end Alembic commands ###
